services:
  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"

  db:
    build:
      context: .
      dockerfile: database/Postgres.Dockerfile
      args:
        REGISTRY_PATH: ${REGISTRY_PATH}
    ports:
      - "${POSTGRES_PORT}:5432"


  liquibase:
    build:
      context: .
      dockerfile: database/Liquibase.Dockerfile
      target: base
      args:
        REGISTRY_PATH: ${REGISTRY_PATH}
    volumes:
      - "./database/changelog:/liquibase/changelog"
      - "./database/changelogDocs:/liquibase/changelogDocs"

  backend:
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.rule=HostRegexp(`www.${SERVER_NAME}`) || Host(`${SERVER_NAME}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=3333"
      - "traefik.docker.network=app-net"
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: dev
      args:
        REGISTRY_PATH: ${REGISTRY_PATH}
        PROJECT: backend
    ports:
      - "${API_PORT}:3333"  # backend
      - "9229:9229"         # default debug port
    volumes:
      - "./apps/backend/src:/usr/src/coding-box-base/apps/backend/src"
      - "backend_vol:/usr/src/coding-box/packages"
    command:
      - "serve"
      - "backend"
      - "--host=backend"

  frontend:
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=HostRegexp(`www.${SERVER_NAME}`) || Host(`${SERVER_NAME}`)"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
      - "traefik.docker.network=app-net"
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: dev
      args:
        REGISTRY_PATH: ${REGISTRY_PATH}
        PROJECT: frontend
    ports:
      - "${HTTP_PORT}:8080"
    volumes:
      - "./apps/frontend/src:/usr/src/coding-box-base/apps/frontend/src"
    command:
      - "serve"
      - "frontend"
      - "--host=frontend"
      - "--port=8080"
